/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package DVTProject;

/**
 *
 * @author dhiyas
 */
public class CreditCardPayingScreen extends javax.swing.JFrame {

    /**
     * Creates new form CreditCardPayingScreen
     */
    public CreditCardPayingScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        JLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        FinishPaymentBut = new javax.swing.JButton();
        sendReceiptRB = new javax.swing.JRadioButton();
        cardNumberTF = new javax.swing.JTextField();
        cardHolderNameTF = new javax.swing.JTextField();
        CVVTF = new javax.swing.JTextField();
        cardHolderNameLab = new javax.swing.JLabel();
        emailLab = new javax.swing.JLabel();
        emailTF = new javax.swing.JTextField();
        cardNumberLab = new javax.swing.JLabel();
        CVVTF1 = new javax.swing.JTextField();
        expiryDateLab = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        CVVTF2 = new javax.swing.JTextField();
        CVVLab = new javax.swing.JLabel();
        amountLab = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        JLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        JLabel7.setForeground(new java.awt.Color(255, 255, 255));
        JLabel7.setText("CVV");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Card Number");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Card holder Name");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Secure Credit Card Payment ");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Expiry Date (MM/YY)");

        FinishPaymentBut.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        FinishPaymentBut.setForeground(new java.awt.Color(0, 102, 0));
        FinishPaymentBut.setText("Finish payment");
        FinishPaymentBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FinishPaymentButActionPerformed(evt);
            }
        });

        sendReceiptRB.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        sendReceiptRB.setForeground(new java.awt.Color(255, 255, 255));
        sendReceiptRB.setText("Send billing receipt to email");
        sendReceiptRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendReceiptRBActionPerformed(evt);
            }
        });

        cardNumberTF.setForeground(new java.awt.Color(0, 0, 0));
        cardNumberTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cardNumberTFActionPerformed(evt);
            }
        });

        cardHolderNameTF.setForeground(new java.awt.Color(0, 0, 0));
        cardHolderNameTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cardHolderNameTFActionPerformed(evt);
            }
        });

        CVVTF.setForeground(new java.awt.Color(0, 0, 0));
        CVVTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CVVTFActionPerformed(evt);
            }
        });

        cardHolderNameLab.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cardHolderNameLab.setForeground(new java.awt.Color(255, 0, 0));
        cardHolderNameLab.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        emailLab.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        emailLab.setForeground(new java.awt.Color(255, 255, 255));
        emailLab.setText("Email: ");

        emailTF.setForeground(new java.awt.Color(0, 0, 0));
        emailTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailTFActionPerformed(evt);
            }
        });

        cardNumberLab.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cardNumberLab.setForeground(new java.awt.Color(255, 0, 0));
        cardNumberLab.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        CVVTF1.setForeground(new java.awt.Color(0, 0, 0));
        CVVTF1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CVVTF1ActionPerformed(evt);
            }
        });

        expiryDateLab.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        expiryDateLab.setForeground(new java.awt.Color(255, 0, 0));
        expiryDateLab.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Amount:");

        CVVTF2.setForeground(new java.awt.Color(0, 0, 0));
        CVVTF2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CVVTF2ActionPerformed(evt);
            }
        });

        CVVLab.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        CVVLab.setForeground(new java.awt.Color(255, 0, 0));
        CVVLab.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        amountLab.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        amountLab.setForeground(new java.awt.Color(255, 0, 0));
        amountLab.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(61, 61, 61)
                                .addComponent(jLabel1))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(JLabel7)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel6)
                                        .addComponent(jLabel5))
                                    .addGap(69, 69, 69)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(cardHolderNameTF)
                                        .addComponent(CVVTF1, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(CVVTF)
                                        .addComponent(CVVTF2)
                                        .addComponent(cardNumberTF)))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(sendReceiptRB)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(emailLab)
                                            .addGap(18, 18, 18)
                                            .addComponent(emailTF, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGap(0, 0, Short.MAX_VALUE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addGap(0, 0, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(CVVLab, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(FinishPaymentBut, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(expiryDateLab, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(amountLab, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 374, Short.MAX_VALUE))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 130, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cardHolderNameLab, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cardNumberLab, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(74, 74, 74))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(62, 62, 62)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cardHolderNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cardHolderNameLab, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(cardNumberTF, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cardNumberLab, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(CVVTF1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(expiryDateLab, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JLabel7)
                    .addComponent(CVVTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CVVLab, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(CVVTF2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(amountLab, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(FinishPaymentBut)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sendReceiptRB)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailLab))
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FinishPaymentButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FinishPaymentButActionPerformed
        // TODO add your handling code here:
        
        //chcecks for cvv
        //do not need to check the cvv of the output
        String cvvLengthOutput= CreditCardPayingScreenBACKEND.checkCVV(CVVTF.getText());
        System.out.println(CVVTF.getText());
        if (!cvvLengthOutput.equals("valid")) {
            CVVLab.setText(cvvLengthOutput);
        }else{
            CVVLab.setText("");
        }

        
        //checks for card holder name
        String onlyLettersInNameOutput = CreditCardPayingScreenBACKEND.checkCardHolderName(cardHolderNameTF.getText(), 3);
        if (!onlyLettersInNameOutput.equals("valid")) {
            System.out.println(onlyLettersInNameOutput);
            cardHolderNameLab.setText(onlyLettersInNameOutput);
        }else{
            cardHolderNameLab.setText("");
        }
        
    }//GEN-LAST:event_FinishPaymentButActionPerformed

    private void sendReceiptRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendReceiptRBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sendReceiptRBActionPerformed

    private void cardHolderNameTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cardHolderNameTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cardHolderNameTFActionPerformed

    private void cardNumberTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cardNumberTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cardNumberTFActionPerformed

    private void CVVTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CVVTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CVVTFActionPerformed

    private void emailTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailTFActionPerformed

    private void CVVTF1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CVVTF1ActionPerformed
        // TODO add your handling code here:
        //sakjhdkjahewkj
    }//GEN-LAST:event_CVVTF1ActionPerformed

    private void CVVTF2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CVVTF2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CVVTF2ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreditCardPayingScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreditCardPayingScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreditCardPayingScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreditCardPayingScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreditCardPayingScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CVVLab;
    private javax.swing.JTextField CVVTF;
    private javax.swing.JTextField CVVTF1;
    private javax.swing.JTextField CVVTF2;
    private javax.swing.JButton FinishPaymentBut;
    private javax.swing.JLabel JLabel7;
    private javax.swing.JLabel amountLab;
    private javax.swing.JLabel cardHolderNameLab;
    private javax.swing.JTextField cardHolderNameTF;
    private javax.swing.JLabel cardNumberLab;
    private javax.swing.JTextField cardNumberTF;
    private javax.swing.JLabel emailLab;
    private javax.swing.JTextField emailTF;
    private javax.swing.JLabel expiryDateLab;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton sendReceiptRB;
    // End of variables declaration//GEN-END:variables
}
